"""Exact saved results, generated by the API engine and content-keyed inputs."""
import sys,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT))
from engine.scenario import compute
from engine.schemas import ScenarioInput

def main():
    target=ROOT/'public/data/scenarios';target.mkdir(parents=True,exist_ok=True);index=[]
    requests=[ScenarioInput(level_m=x/2) for x in range(17)]+[ScenarioInput(level_m=x/2,shelter_overrides={'shelter-5':{'open':True}}) for x in range(17)]
    first=compute(ScenarioInput());demo_edge=first['allocations'][0]['edge_ids'][0]
    requests.append(ScenarioInput(closed_edge_ids=[demo_edge]))
    for request in requests:
        result=compute(request);url=f'/data/scenarios/{result["scenario_id"]}.json';(ROOT/'public'/url.lstrip('/')).write_text(json.dumps(result,separators=(',',':')))
        index.append({'input':result['input'],'dataset_version':result['dataset_version'],'url':url})
    (target/'index.json').write_text(json.dumps(index,separators=(',',':')))
    (ROOT/'public/data/demo.json').write_text(json.dumps({'closure_edge_id':demo_edge,'description':'Closes the first directed link of the first default allocation route. The reverse direction, if present, remains open.'}))
    print('Exported',len(index),'exact scenarios; demo closure',demo_edge)
if __name__=='__main__':main()
